# this configures the allowable standard branch name prefixes
# (used by workflow\branch-name-check.yml)
allowed_prefixes:
  - bugfix/
  - chore/
  - docs/
  - feature/
  - hotfix/
  - refactor/
 